/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cpu1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cpu1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, -0.086]} scale={0.091}>
        <mesh geometry={nodes.Plane.geometry} material={materials['PrintedCircuitBoard.001']} rotation={[0, 0, -1.114]} scale={10.971} />
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} />
    </group>
  )
}

useGLTF.preload('/cpu1.glb')
