/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cpu2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cpu2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} />
    </group>
  )
}

useGLTF.preload('/cpu2.glb')
