/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cpu5.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/cpu5.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={6830} decay={2} position={[0, 1.409, 0]} rotation={[-2.176, 0.145, 0.045]} target={nodes.Sun.target}>
        <primitive object={nodes.Sun.target} position={[0, 0, -1]} />
      </directionalLight>
      <mesh geometry={nodes.Plane002.geometry} material={materials.normalTest} />
    </group>
  )
}

useGLTF.preload('/cpu5.glb')
